engines:
  fixme:
    enabled: true
  eslint:
    enabled: false
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths: []
exclude_paths: []